---
- name: Write default config
  notify:
    - Restart solidfire-exporter
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/solidfire-exporter
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - solidfire-exporter

- name: Prepare service file
  notify:
    - Restart solidfire-exporter
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/solidfire-exporter.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - solidfire-exporter

- name: Pull docker image
  when:
    - solidfire_exporter_pull_image
  community.docker.docker_image:
    name: "{{ solidfire_exporter_image }}"
    source: pull
  tags:
    - solidfire-exporter

- name: Create docker network
  when:
    - false if solidfire_exporter_network is none else (solidfire_exporter_network | length > 0)| default(false)
  community.docker.docker_network:
    name: '{{ solidfire_exporter_network }}'
  tags:
    - solidfire-exporter

- name: Start exporter service
  ansible.builtin.systemd:
    name: solidfire-exporter
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - solidfire-exporter

...
